### ISSUE TITLE
add

### ISSUE THREAD

**Issue by coco413** [c0ny1/vulstudy#2]
补充一些BWVS、DoraBox、Wooyun_DVWA、 ZVulDrill、 XVWA 、OWASP Security Shepherd、WebGoat、WAVSEP、各类xss挑战

**Comment by c0ny1** [comment]
@coco413 感谢推荐，最近抽空去做一下这些靶场的题目。感觉确实不错的，会尽快制作成docker镜像，集成到项目中。
